-- 事件
CONST_EVENT = {
    beAttackReady = "beAttackReady", --- 准备被攻击
    attack = "attack",  --- 造成攻击
    beAttack = "beAttack",  --- 承受攻击
    skillStudy = "skillStudy",  --- 学习技能
    skillReady = "skillReady",  --- 准备施放技能
    skillCast = "skillCast",    --- 开始施放技能
    skillEffect = "skillEffect",    --- 发动技能效果
    skillStop = "skillStop",    --- 停止施放技能
    skillFinish = "skillFinish",    --- 施放技能结束
    itemUsed = "itemUsed",  --- 单位使用物品
    itemSell = "itemSell",  --- 出售物品(商店卖给玩家)
    unitSell = "unitSell",  --- 出售单位(商店卖给玩家)
    itemDrop = "itemDrop",  --- 丢弃(传递)物品
    itemPawn = "itemPawn",  --- 抵押物品（玩家把物品扔给商店）
    itemGet = "itemGet",    --- 获得物品
    itemDestroy = "itemDestroy",    --- 物品被破坏
    itemOverSlot = "itemOverSlot",
    damage = "damage",  --- 造成攻击
    beDamage = "beDamage",  --- 承受伤害
    dead = "dead",  --- 死亡时
    kill = "kill",  --- 杀敌时
    reborn = "reborn",  --- 复活时(必须使用 hunit.reborn 方法才能嵌入到事件系统)
    levelUp = "levelUp",    --- 提升等级时
    exp = "exp",    --- 获得经验时
    enterUnitRange = "enterUnitRange",  --- 进入某单位（whichUnit）半径范围内
    enterRect = "enterRect",    --- 进入某区域
    leaveRect = "leaveRect",    --- 离开某区域
    chat = "chat",  
    esc = "esc",    --- 按ESC
    selection = "selection",    --- 玩家选择单位(点击了qty次)
    deSelection = "deSelection",    --- 玩家取消选择单位
    upgradeStart = "upgradeStart",  --- 建筑升级开始时
    upgradeCancel = "upgradeCancel",    --- 建筑升级取消时
    upgradeFinish = "upgradeFinish",    --- 建筑升级完成时
    constructStart = "constructStart",  --- 任意建筑建造开始时
    constructCancel = "constructCancel",    --- 任意建筑建造取消时
    constructFinish = "constructFinish",    --- 任意建筑建造完成时
    pickHero = "pickHero",  --- 任意单位经过hero方法被玩家所挑选为英雄时(注意这是全局事件)
    playerLeave = "playerLeave",    --- 玩家离开游戏事件(注意这是全局事件)
    playerResourceChange = "playerResourceChange",  --- 玩家资源变动
    destructableDestroy = "destructableDestroy",    --- 可破坏物死亡
    holdOn = "holdOn",  --- 当单位发布驻扎(H)命令,只有真人玩家的单位有此事件
    stop = "stop",  --- 当单位发布停止(S)命令,只有真人玩家的单位有此事件
    changeOwner = "changeOwner",    --- 任意单位改变所有者时
}