---@单位文本
ITEM = {
    abilList = "主动技能ID列表",
    Requires = "科技树",
    Requiresamount = "科技树-需求值",
    Name = "名称",
    Description = "描述",
    Tip = "描述标题",
    Ubertip = "说明",
    Hotkey = "热键",
    Art = "图标",
    scale = "模型大小",
    file = "模型文件路径",
    Buttonpos_1 = "按钮位置 - 普通 (X)",
    Buttonpos_2 = "按钮位置 - 普通 (Y)",
    selSize = "选择圈大小",
    colorR = "红",
    colorG = "绿",
    colorB = "蓝",
    armor = "装甲类型",
    Level = "等级",
    oldLevel = "等级(旧)",
    class = "分类",
    goldcost = "黄金",
    lumbercost = "木头",
    HP = "生命",
    stockStart = "开始库存",
    stockRegen = "补货周期",
    stockMax = "最大库存",
    prio = "优先权",
    cooldownID = "AEar", -- CD间隔组
    ignoreCD  = "0", -- 无视CD间隔
    morph = "有效的物品转换目标",
    drop = "死亡时掉落",
    powerup = "捡到时自动使用",
    sellable = "可以出售",
    pawnable = "可以抵押",
    droppable = "可以丢弃",
    pickRandom = "可以作为随机物品",
    uses = "使用次数",
    perishable = "使用后完全消失",
    usable = "主动使用",
}

---@Slk原生物编字段--此项是针对创建单位
un = {
    abilList = "主动技能ID列表",
    Requires = "科技树",
    Requiresamount = "科技树-需求值",
    Name = "名称",
    Description = "描述",
    Tip = "描述标题",
    Ubertip = "说明",
    Hotkey = "热键",
    Art = "图标",
    scale = "模型大小",
    file = "模型文件路径",
    Buttonpos = "X坐标",
    Buttonpos = "Y坐标",
    UnButtonpos = "X坐标-关闭",
    UnButtonpos = "Y坐标-关闭",
    selSize = "选择圈大小",
    colorR = "红",
    colorG = "绿",
    colorB = "蓝",
    armor = "装甲类型",
    Level = "等级",
    oldLevel = "等级(旧)",
    class = "分类",
    goldcost = "黄金",
    lumbercost = "木头",
    HP = "生命",
    stockStart = "开始库存",
    stockRegen = "补货周期",
    stockMax = "最大库存",
    prio = "优先权",
    morph = "有效的物品转换目标",
    drop = "死亡时掉落",
    powerup = "捡到时自动使用",
    sellable = "可以出售",
    pawnable = "可以抵押",
    droppable = "可以丢弃",
    pickRandom = "可以作为随机物品",
    uses = "使用次数",
    perishable = "使用后完全消失",
    usable = "主动使用",
    level = "等级",
    race = "种族",
    type = "类别",
    manaN = "最大魔法值",
    regenMana = "魔法恢复",
    mana0 = "初始魔法",
    regenHP = "生命恢复",
    regenType = "生命恢复类型",
    fmade = "提供人口",
    fused = "占用人口",
    stockStart = "雇佣开始时间",
    stockRegen = "雇佣开始间隔",
    stockMax = "最大库存",
    sight = "白天视野",
    nsight = "夜晚视野",
    collision = "接触体积",
    modelScale = "模型缩放",
    fileVerFlags = "模型文件版本",
    scaleBull = "缩放投射物",
    scale = "选择圈缩放",
    selZ = "选择圈高度",
    selCircOnWater = "选择圈在水面上",
    red = "红",
    green = "绿",
    blue = "蓝",
    occH = "闭塞高度",
    maxPitch = "X轴最大旋转角度",
    maxRoll = "Y轴最大旋转角度",
    impactZ = "射弹碰撞偏移Z",
    impactSwimZ = "射弹碰撞偏移Z深水",
    launchX = "射弹偏移X",
    launchY = "射弹偏移Y",
    launchZ = "射弹偏移Z",
    launchSwimZ = "射弹偏移Z深水",
    unitSound = "单位声音",
    RandomSoundLabel = "声音随机",
    MovementSoundLabel = "声音移动",
    LoopingSoundFadeOut = "声音渐出",
    LoopingSoundFadeIn = "声音渐入",
    auto = "主动自动技能ID",
    Sellitems = "售出物品",
    Sellunits = "售出单位",
    Markitems = "制造物品",
    Builds = "可建造单位",
    Specialart = "特殊效果",
    unitShadow = "单位阴影",
    buildingShadow = "建筑阴影",
    shadowH = "阴影H",
    shadowW = "阴影W",
    shadowX = "阴影X",
    shadowY = "阴影Y",
    shadowOnWater = "深水有阴影",
    death = "死亡时间",
    deathType = "死亡类型",
    movetp = "移动类型",
    moveHeight = "移动高度",
    moveFloor = "最小高度",
    spd = "基础速度",
    maxSpd = "最大速度",
    minSpd = "最小速度",
    turnRate = "转身速率",
    acquire = "主动攻击范围",
    minRange = "最小攻击范围",
    weapsOn = "允许攻击",
    Missileart = "箭矢模型",
    Missilespeed = "箭矢速度",
    Missilearc = "箭矢弧度",
    MissileHoming = "箭矢自导",
    targs = "目标允许",
    atkType = "攻击类型",
    weapTp = "武器类型",
    weapType = "武器声音",
    spillRadius = "穿透伤害范围",
    spillDist = "穿透距离",
    damageLoss = "伤害衰减参数",
    showUI = "显示攻击UI",
    backSw = "攻击后摇",
    dmgpt = "攻击前摇",
    rangeN = "攻击范围",
    RngBuff = "攻击范围缓冲",
    dmgplus = "基础伤害",
    dmgUp = "攻击科技升级",
    sides = "伤害骰子面数",
    dice = "伤害骰子数量",
    splashTargs = "范围影响目标",
    cool = "攻击间隔",
    Farea = "全伤害范围",
    targCount = "最大目标数",
    Qfact = "小伤害参数",
    Qarea = "小伤害范围",
    Hfact = "中伤害参数",
    Harea = "中伤害范围",
    defType = "护甲类型",
    defUp = "护甲科技升级",
    def = "基础护甲",
    armor = "装甲类型（被击声音）",
    targType = "作为目标类型",
    Propernames = "英雄称谓",
    nameCount = "英雄称谓个数",
    Awakentip = "英雄唤醒提示",
    Revivetip = "英雄重生提示",
    Primary = "主属性",
    STR = "力量",
    STRplus = "力量成长",
    AGI = "敏捷",
    AGIplus = "敏捷成长",
    INT = "智力",
    INTplus = "智力成长",
    heroAbilList = "英雄技能ID列表",
    hideHeroMinimap = "隐藏英雄小地图",
    hideHeroBar = "隐藏英雄栏图标",
    hideHeroDeathMsg = "隐藏英雄死亡信息",
    Requiresacount = "科技树-使用等级数",
    Requires = "科技树-等级",
    Reviveat = "指定复活点",
    buffRadius = "路径-AI放置范围",
    buffType = "路径-AI放置类型",
    Revive = "可复活单位",
    Trains = "可训练单位",
    Upgrade = "可升级建筑",
    requirePlace = "路径-放置不允许",
    preventPlace = "路径-放置要求",
    requireWaterRadius = "路径-放置要求距离水的范围",
    pathTex = "路径纹理",
    uberSplat = "建筑地面纹理",
    nbrandom = "中立-可作为随机建筑",
    nbmmlcon = "中立-显示小地图",
    canBuildOn = "能被其他建筑建造",
    isBuildOn = "能建造在其他建筑上",
    tilesets = "大地图-地形设置",
    special = "大地图-分类-特殊",
    campaign = "大地图-分类-战役",
    inEditor = "大地图-可放置",
    dropItems = "大地图-死亡掉落物品",
    hostilePal = "大地图-可作为中立敌对",
    useClickHelper = "大地图-使用点击帮助",
    tilesetSpecific = "大地图-有地形指定数据",
    DependencyOr = "科技树-从属等价物",
    Researches = "科技树-可研究项目",
    upgrades = "使用的科技",
    EditorSuffix = "编辑器后缀",
    Casterupgradename = "魔法升级名字",
    Casterupgradetip = "魔法升级说明",
    Castrerupgradeart = "魔法升级图标",
    ScoreScreenIcon = "图标-记分屏",
    animProps = "要求动画名",
    Attachmentanimprops = "要求动画名-附加动画",
    Attachmentlinkprops = "要求动画名-链接名",
    Boneprops = "要求骨骼名",
    castpt = "动画-施法前摇",
    castbsw = "动画-施法后摇",
    blend = "动画-混合时间（秒）",
    run = "动画-跑步",
    walk = "动画-行走",
    propWin = "动画-转向角度",
    orientInterp = "动画-转向补正",
    teamColor = "队伍颜色",
    customTeamColor = "允许更改队伍颜色",
    elevPts = "高度变化-采样点数量",
    elevRad = "高度变化-采样范围",
    fogRad = "战争迷雾-采样范围",
    fatLOS = "不可见区域显示单位",
    repulse = "组群分离-允许",
    repulsePrio = "组群分离-优先",
    repulseParam = "组群分离-参数",
    repulseGroup = "组群分离-组号",
    isbldg = "是一个建筑",
    bldtm = "建造时间",
    bountyplus = "黄金奖励-值",
    bountysides = "黄金奖励-骰子面数",
    bountydice = "黄金奖励-骰子数量",
    goldRep = "修理黄金消耗",
    lumberRep = "修理木材消耗",
    reptm = "修理时间",
    lumberbountyplus = "木材奖励-值",
    lumberbountysides = "木材奖励-骰子面数",
    lumberbountydice = "木材奖励-骰子数量",
    cargoSize = "运输尺寸",
    hideOnMinimap = "隐藏小地图显示",
    points = "单位附加值",
    prio = "编队优先权",
    formation = "队形排列",
    canFlee = "可以逃跑",
    canSleep = "可以睡眠",
    checkDep = "科技树-检查等价所属",
    Effectsound = "声效-音效",
    Effectsoundlooped = "声效-音效（循环）",
    Researchtip = "学习技能提示",
    Researchubertip = "学习技能描述",
    Unorder = "命令-关闭",
    Orderon = "命令-激活",
    Order = "命令串",
    Orderoff = "命令-取消激活",
    Unhotkey = "热键-关闭",
    Researchhotkey = "热键-学习",
    Researchbuttonpos1 = "X坐标-学习",
    Researchbuttonpos2 = "Y坐标-学习",
    Unart = "图标-关闭",
    Researchart = "图标-学习",
    SpecialArt = "效果-特殊",
    Specialattach = "效果-特殊附加点",
    LightningEffect = "效果-闪电效果",
    EffectArt = "效果-目标点",
    TargetArt = "效果-目标",
    Targetattachcount = "效果-目标-附加数量",
    Targetattach = "效果-目标-附加",
    Areaeffectart = "效果-区域",
    Animnames = "施法动作",
    CasterArt = "效果-施法者",
    Casterattachcount = "效果-施法者-附加数量",
    Casterattach = "效果-施法者-附加",
    hero = "是否英雄技能",
    item = "是否物品技能",
    levels = "等级",
    reqLevel = "等级要求",
    levelSkip = "学习跳等级",
    priority = "魔法偷取优先级",
    BuffID = "魔法效果",
    EfctID = "区域持续效果",
    DataA = "数据A",    -- 使用后暂停时间
    DataB = "数据B",    -- 目标 0无目标,1单位目标,2点目标,3范围目标
    DataC = "数据C",    -- 选项 应该是选择显示方式默认0
    DataD = "数据D",    -- 动作储蓄期间 技能框选 0无目标,1单位目标,2点目标,3范围目标
    DataE = "数据E",    -- 使其他技能无效
    DataF = "数据F",    -- 指令,同一指令视为一个技能
    Cast = "施法时间",
    Cool = "冷却时间",
    Dur = "持续时间",
    HeroDur = "持续时间（英雄）",
    Cost = "魔法消耗",
    Rng = "施法距离"  ,
    Area = "施法范围",
}
---@事件文本
CONST_EVENT = {
    beAttackReady = "beAttackReady",
    attack = "attack",
    beAttack = "beAttack",
    skillStudy = "skillStudy",
    skillReady = "skillReady",
    skillCast = "skillCast",
    skillEffect = "skillEffect",
    skillStop = "skillStop",
    skillFinish = "skillFinish",
    itemUsed = "itemUsed",
    itemSell = "itemSell",
    unitSell = "unitSell",
    itemDrop = "itemDrop",
    itemPawn = "itemPawn",
    itemGet = "itemGet",
    itemDestroy = "itemDestroy",
    itemOverSlot = "itemOverSlot",
    damage = "damage",
    beDamage = "beDamage",
    dead = "dead",
    kill = "kill",
    reborn = "reborn",
    levelUp = "levelUp",
    exp = "exp",
    enterUnitRange = "enterUnitRange",
    enterRect = "enterRect",
    leaveRect = "leaveRect",
    chat = "chat",
    esc = "esc",
    selection = "selection",
    deSelection = "deSelection",
    upgradeStart = "upgradeStart",
    upgradeCancel = "upgradeCancel",
    upgradeFinish = "upgradeFinish",
    constructStart = "constructStart",
    constructCancel = "constructCancel",
    constructFinish = "constructFinish",
    pickHero = "pickHero",
    playerLeave = "playerLeave",
    playerResourceChange = "playerResourceChange",
    destructableDestroy = "destructableDestroy",
    holdOn = "holdOn",
    stop = "stop",
    changeOwner = "changeOwner",
}

---@物品属性配置器
ATTR_CONFIGURATOR({
    { "life", "生命", 0 },
    { "mana", "魔法", 0 },
    { "move", "移动", 0 },
    { "defend", "护甲", 0 },
    { "defend_white", "基础护甲", 0 },
    { "defend_green", "附加护甲", 0 },
    { "attack_speed", "攻速", 0 },
    { "attack_space", "攻击间隔", 0 },
    { "attack_space_origin", "攻击间隔", 0 },
    { "attack", "攻击", 0 },
    { "attack_white", "基础攻击", 0 },
    { "attack_green", "附加攻击", 0 },
    { "attack_range", "攻击范围", 0 },
    { "attack_range_acquire", "主动攻击范围", 0 },
    { "str", "力量", 0 },
    { "agi", "敏捷", 0 },
    { "int", "智力", 0 },
    { "str_green", "附加力量", 0 },
    { "agi_green", "附加敏捷", 0 },
    { "int_green", "附加智力", 0 },
    { "str_white", "本体力量", 0 },
    { "agi_white", "本体敏捷", 0 },
    { "int_white", "本体智力", 0 },
    { "life_back", "生命恢复", 0 },
    { "mana_back", "魔法恢复", 0 },
    { "reborn", "复活时间", -999 },
    -- 本身是在player实现
    { "gold_ratio", "黄金获得率", 0 },
    { "lumber_ratio", "木头获得率", 0 },
    { "exp_ratio", "经验获得率", 0 },
    { "sell_ratio", "售卖比率", 0 },
})

---@物品分类
CONST_ITEM_CLASS = {
    Permanent = "永久",
    Charged = "可充",
    PowerUp = "力量提升",
    Artifact = "人造",
    Purchasable = "可购买",
    Campaign = "战役",
    Miscellaneous = "混杂",
}

---@通魔可用字符串，可以根据这些串串写个自动分配方法
ORDER_STR = {
    "Carrionscarabs",
    "Locustswarm",
    "Serpentward",
    "Vengeance",
    "absorbmana",
    "acidbomb",
    "ambush",
    "animatedead",
    "antimagicshell",
    "attributemodskill",
    "autodispel",
    "avatar",
    "awaken",
    "banish",
    "bash",
    "battleroar",
    "battlestations",
    "bearform",
    "berserk",
    "blackarrow",
    "blink",
    "blizzard",
    "bloodlust",
    "breathoffire",
    "build",
    "burrow",
    "cannibalize",
    "carrionswarm",
    "chainlightning",
    "channel",
    "charm",
    "chemicalrage",
    "cloudoffog",
    "clusterrockets",
    "controlmagic",
    "corporealform",
    "corrosivebreath",
    "creepdevour",
    "creepsleep",
    "creepthunderbolt",
    "creepthunderclap",
    "cripple",
    "curse",
    "cyclone",
    "darkconversion",
    "darkritual",
    "darksummoning",
    "deathanddecay",
    "deathcoil",
    "deathpact",
    "decouple",
    "defend",
    "demolish",
    "detonate",
    "devour",
    "dispel",
    "doom",
    "drunkenhaze",
    "earthquake",
    "eattree",
    "elementalfury",
    "engineeringupgrade",
    "ensnare",
    "entangle",
    "entanglingroots",
    "etherealform",
    "evileye",
    "faeriefire",
    "fanofknives",
    "farsight",
    "flamestrike",
    "flamingarrows",
    "flare",
    "forceofnature",
    "forkedlightning",
    "freezingbreath",
    "frenzy",
    "frostarmor",
    "frostnova",
    "grabtree",
    "harvest",
    "heal",
    "healingspray",
    "healingward",
    "healingwave",
    "hex",
    "holybolt",
    "howlofterror",
    "humanbuild",
    "immolation",
    "impale",
    "incinerate",
    "incineratearrow",
    "inferno",
    "innerfire",
    "invisibility",
    "load",
    "loadcorpse",
    "magicdefense",
    "magicleash",
    "magicundefense",
    "manaburn",
    "manaflareoff",
    "manaflareon",
    "massteleport",
    "metamorphosis",
    "militia",
    "militiaoff",
    "mindrot",
    "mirrorimage",
    "monsoon",
    "nagabuild",
    "nightelfbuild",
    "orcbuild",
    "parasite",
    "phaseshift",
    "poisonarrowstarg",
    "polymorph",
    "possession",
    "purge",
    "rainoffire",
    "raisedead",
    "ravenform",
    "rejuvination",
    "renew",
    "repair",
    "replenish",
    "replenishlife",
    "restoration",
    "resurrection",
    "revive",
    "roar",
    "robogoblin",
    "root",
    "sacrifice",
    "scout",
    "selfdestruct",
    "sentinel",
    "shadowstrike",
    "shockwave",
    "silence",
    "sleep",
    "slimemonster",
    "slow",
    "soulburn",
    "soulpreservation",
    "spellsteal",
    "sphinxform",
    "spiritlink",
    "spiritlinkaoe",
    "spiritofvengeance",
    "spiritwolf",
    "stampede",
    "standdown",
    "starfall",
    "stasistrap",
    "stomp",
    "stoneform",
    "submerge",
    "summonfactory",
    "summongrizzly",
    "summonphoenix",
    "summonquillbeast",
    "summonwareagle",
    "taunt",
    "thunderbolt",
    "thunderclap",
    "tornado",
    "townbelloff",
    "townbellon",
    "tranquility",
    "transmute",
    "unbearform",
    "unburrow",
    "uncorporealform",
    "undeadbuild",
    "undefend",
    "unetherealform",
    "unflamingarrows",
    "unholyfrenzy",
    "unimmolation",
    "unload",
    "unloadcorpse",
    "unravenform",
    "unrobogoblin",
    "unroot",
    "unsphinxform",
    "unstableconcoction",
    "unstoneform",
    "unsubmerge",
    "unsummon",
    "volcano",
    "voodoo",
    "ward",
    "waterelemental",
    "wateryminion",
    "web",
    "whirlwind",
    "windwalk",
}


---@作用目标
CONST_TARGET_LABEL = {
    notself = "别人",
    debris = "残骸",
    alive = "存活",
    ground = "地面",
    terrain = "地形",
    enemies = "敌人",
    enemy = "敌人",
    ancient = "古树",
    mechanical = "机械类",
    structure = "建筑",
    vuln = "可攻击的",
    air = "空中",
    allies = "联盟",
    none = "没有",
    well = "墙",
    bridge = "桥",
    ward = "守卫",
    tree = "树木",
    dead = "死亡",
    player = "玩家单位",
    invu = "无敌",
    item = "物品",
    hero = "英雄",
    friend = "友军",
    organic = "有机生物",
    neutral = "中立",
    decoration = "装饰物",
    sapper = "自爆工兵",
    self = "自己",
    nonancient = "非古树",
    nonhero = "非英雄",
    nonsapper = "非自爆兵",
}